export declare const MarkdownStr12: string;
export declare const MarkdownStr_echart: string;
export declare const MarkdownStr_katex: string;
export declare const MarkdownStr_think: string;
export declare const MarkdownStr_url: string;
export declare const MarkdownStr_hardbreak: string;
export declare const MarkdownStr_url2: string;
export declare const MarkdownStr_fence: string;
export declare const MarkdownStr_code: string;
export declare const MarkdownStr_code2: string;
export declare const MarkdownStr_svg: string;
export declare const MarkdownStr_echarts2: string;
export declare const MarkdownStr_mermaid = "#### \u6D4B\u8BD5Mermaid\u6548\u679C\n\n```mermaid\ngitGraph\n    commit\n    commit\n    branch develop\n    checkout develop\n    commit\n    commit\n    checkout main\n    merge develop\n    commit\n    commit\n```\n\n```mermaid\nflowchart TD\n    A[Christmas] -->|Get money| B(Go shopping)\n    B --> C{Let me think}\n    C -->|One| D[Laptop]\n    C -->|Two| E[iPhone]\n    C -->|Three| F[fa:fa-ca\n```\n\n```mermaid\npie title Pets adopted by volunteers\n    \"Dogs\" : 386\n    \"Cats\" : 85\n    \"Rats\" : 15\n```\n";
