export declare const MarkdownStr12: string;
export declare const MarkdownStr_echart: string;
export declare const MarkdownStr_katex: string;
export declare const MarkdownStr_think: string;
export declare const MarkdownStr_url: string;
export declare const MarkdownStr_hardbreak: string;
export declare const MarkdownStr_url2: string;
export declare const MarkdownStr_fence: string;
export declare const MarkdownStr_code: string;
export declare const MarkdownStr_svg: string;
export declare const MarkdownStr_echarts2: string;
export declare const MarkdownStr_mermaid = "# \u6D4B\u8BD5Mermaid\u6548\u679C\n\n```mermaid\ngitGraph\n    commit\n    commit\n    branch develop\n    checkout develop\n    commit\n    commit\n    checkout main\n    merge develop\n    commit\n    commit\n```\n\n```mermaid\nflowchart TD\n    A[Christmas] -->|Get money| B(Go shopping)\n    B --> C{Let me think}\n    C -->|One| D[Laptop]\n    C -->|Two| E[iPhone]\n    C -->|Three| F[fa:fa-ca\n```\n\n```mermaid\n---\ntitle: \"TCP Packet\"\n---\npacket-beta\n  0-15: \"Source Port\"\n  16-31: \"Destination Port\"\n  32-63: \"Sequence Number\"\n  64-95: \"Acknowledgment Number\"\n  96-99: \"Data Offset\"\n  100-105: \"Reserved\"\n  106: \"URG\"\n  107: \"ACK\"\n  108: \"PSH\"\n  109: \"RST\"\n  110: \"SYN\"\n  111: \"FIN\"\n  112-127: \"Window\"\n  128-143: \"Checksum\"\n  144-159: \"Urgent Pointer\"\n  160-191: \"(Options and Padding)\"\n  192-255: \"Data (variable length)\"\n```\n";
